apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: time-share-slots
  labels:
    {{- include "dra-time-share.labels" . | nindent 4 }}
spec:
  selectors:
    - cel:
        expression: "device.driver == '{{ .Values.driverName }}'"
